config/routes.rb
Rails.application.routes.draw do
  root to: 'employees#index'
  resources :purchases, :inventories, :products, :employees

  match '/products/:id', to: 'products#update', via: [:options]
  match '/inventories/:id', to: 'inventories#update', via: [:options]
  match '/purchases/:id', to: 'purchases#update', via: [:options]
  match '/employees/:id', to: 'employees#update', via: [:options]

  scope '/api' do
  	get '/available', to: 'api#get_available_inventory'
  	get '/issued', to: 'api#get_issued_inventory'
  	get '/retired', to: 'api#get_retired_inventory'
  	post '/issue', to: 'api#issue_inventory'
  	post '/return', to: 'api#return_inventory'
  	post '/retire', to: 'api#retire_inventory'
    get '/config', to: 'api#get_config'
  end
  #resources :allotments, except: [:edit, :update, :destroy]
end

app/models/inventory.rb
class Inventory
  include Mongoid::Document

  ###########FIELDS#############
  field :product_id
  field :serial_no
  field :status, default: 'Available'
  field :xid
  field :date, type: Date
  field :prod

  before_save do |doc|
    prod_obj = Product.find(product_id)
    doc.prod = "#{prod_obj.brand} #{prod_obj.equipment} #{prod_obj.model} #{prod_obj.capacity}".rstrip
  end


  ###############INDEX######################

  index({status: 1, serial_no: 1}, {unique: true})


  ########VALIDATIONS###############
  validates :serial_no, presence: true, uniqueness: true
  validates :status, presence: true, inclusion: { in: INVENTORY_STATUSES }
  validates :product_id, presence: true
  validates :xid, presence: true, if: Proc.new {|x| x.status == 'Issued'}
  validates :date, presence: true, unless: Proc.new {|x| x.xid.nil? }
  validate :validate_employee

  def validate_employee
    errors.add(:xid, 'does not belong to a valid employee') if xid and Employee.find_by(xid: xid).nil?
  end


  ############RELATION##########
  belongs_to :product
  belongs_to :employee, foreign_key: :xid, primary_key: :xid


  ############SCOPES############
  scope :available, ->{ where(status: "Available") }
  scope :issued, ->{ where(status: "Issued") }
  scope :retired, ->{ where(status: "Retired") }

end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params[:inventory].permit(:product_id, :serial_no, :status)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inventories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>